name: Lint

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  stylelint:
    name: stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: npm
          cache-dependency-path: |
            package-lock.json
      - run: npm ci
      - uses: reviewdog/action-setup@v1
      - run: reviewdog -version
      - name: stylelint
        env:
          # reviewdogはこの環境変数でTokenを参照する
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            npx stylelint "**/*.{vue,css}" --no-color \
            | reviewdog -f="stylelint" -name="stylelint" -reporter="github-pr-check" -level="error" -filter-mode="nofilter" -fail-on-error="false"
  stylelint2:
    name: runner / stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          reporter: github-pr-review # Change reporter.
          stylelint_input: '**/*.{vue,css}'
