name: Lint

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  stylelint:
    name: stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          reporter: github-pr-review # Change reporter.
          packages: 'stylelint-prettier'
          stylelint_input: '**/*.{vue,css}'
          fail_on_error: true
